name: Run Python Script Safely

on:
  schedule:
    # 每天台灣時間早上 9 點執行 (UTC+8 → UTC 1 點)
    - cron: '*/30 * * * *'
  workflow_dispatch:  # 手動觸發



jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
        pip install beautifulsoup4 requests


    - name: Run Script with Environment Variables
      # 將 GitHub Secret 對應成執行環境的變數
      env:
        CREDENTIALS_INFO: ${{ secrets.CREDENTIALS_INFO }}
        TOKEN_INFO: ${{ secrets.TOKEN_INFO }}
        emailwhitelist: ${{ vars.emailwhitelist }}
      run: |
        python  build_archive.py


    # 新增以下步驟：自動將多層子資料夾打包提交
    - name: Commit and Push Outputs
      env:
        # 使用 GitHub 自動產生的 Token 進行身分驗證，不需額外建立 Secret
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 1. 設定自動提交時的機器人身分
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
        
        # 2. 將指定的輸出資料夾（含所有多層子資料夾）加入暫存區
        # 假設您的輸出資料夾名稱叫 output，請依實際情況修改
        git add log
        git add storage
        git add index.html

        git commit -m "系統自動更新資料夾檔案"
        git push origin main  --force
       

